version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/App/Api/Dockerfile
    ports:
      - "20401:8080"
      - "20402:8081"
    networks:
    - application
    depends_on:
        - mssql-database

  tenantservices:
    image: ${DOCKER_REGISTRY-}tenantservices
    build:
      context: .
      dockerfile: src/Common/TenantServices/Dockerfile
    ports:
      - "30501:8080"
      - "30502:8081"
    networks:
    - application
    depends_on:
        - mssql-database


  report.api:
    image: ${DOCKER_REGISTRY-}reportapi
    build:
      context: .
      dockerfile: src/Report/Report.Api/Dockerfile
    ports:
      - "40601:8080"
      - "40602:8081"
    networks:
    - application
    depends_on:
        - mssql-database

  mssql-database:
    container_name: MsSqlDatabase 
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
        - ./.containers/database:/var/opt/mssql/data    
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sa123_secret_@#TYuiop"   
    ports:
      - "1433:1433"
    networks:
        - application

  rabbitmq-instance:
    container_name: RabbitMQ.MessageBroker
    image: rabbitmq:management
    hostname: mq-message
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      #CELERY_BROKER_URL: "amqp://rabbitmq-instanc:5672"
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
    - application

networks:
  application:
     driver: bridge
        


